#!/bin/bash
set -e

curl -L ${INPUT_URL}/${INPUT_TAG}/${INPUT_ASSET_NAME} > ${GITHUB_WORKSPACE}/${INPUT_ASSET_NAME} \
&& unzip -q ${GITHUB_WORKSPACE}/${INPUT_ASSET_NAME} -d ${GITHUB_WORKSPACE}/${CPP_SDK_DESTINATION} \
&& rm ${GITHUB_WORKSPACE}/${INPUT_ASSET_NAME}
